export const LAST_SELECTED_BTN = 'LAST_SELECTED_BTN'

export const ADD_TITLE = 'ADD_TITLE'
export const UPDATE_ELEMENT_EDIT = 'UPDATE_ELEMENT_EDIT'

export const ADD_ELEMENT_TEXT = 'ADD_ELEMENT_TEXT'
export const ADD_ELEMENT = 'ADD_ELEMENT'
export const REMOVE_ELEMENT = 'REMOVE_ELEMENT'
export const REORDER_ELEMENT = 'REORDER_ELEMENT'

export const FORMAT_ELEMENT = 'FORMAT_ELEMENT'